name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package manager
        id: package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> "$GITHUB_OUTPUT"
            echo "install_command=install" >> "$GITHUB_OUTPUT"
            echo "build_command=build" >> "$GITHUB_OUTPUT"
          elif [ -f "${{ github.workspace }}/package-lock.json" ]; then
            echo "manager=npm" >> "$GITHUB_OUTPUT"
            echo "install_command=install" >> "$GITHUB_OUTPUT"
            echo "build_command=run build" >> "$GITHUB_OUTPUT"
          elif [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
            echo "manager=pnpm" >> "$GITHUB_OUTPUT"
            echo "install_command=install" >> "$GITHUB_OUTPUT"
            echo "build_command=run build" >> "$GITHUB_OUTPUT"
          else
            echo "Unable to determine package manager" >&2
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: ${{ steps.package-manager.outputs.manager }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: ${{ steps.package-manager.outputs.manager }} ${{ steps.package-manager.outputs.install_command }}

      - name: Build
        run: ${{ steps.package-manager.outputs.manager }} ${{ steps.package-manager.outputs.build_command }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
